### ISSUE TITLE
[Bug] Damage apperas on wrong target

### ISSUE THREAD

**Issue by MaelKoT** [bkader/NameplateSCT_WoTLK#2]
![image](https://user-images.githubusercontent.com/2527033/109583376-e1a03c00-7b10-11eb-9e1c-90ad7c2cce99.png)

Sometimes (often) damage lines appears on the wrong opponents who receive this damage.

I know that wotlk has very limited options for interacting with nameplates, and addons cannot figure out who is who when enemies have the same name. But here are completely different names. (maybe problem in my client localization?)

Could it be possible to add something like periodically checking name of nameplate, next to which the damage numbers appear, and name of target that actually takes this damage? Or an additional search for target name, among all displayed nameplates, or something like that ...

_________
Great job, anyway. I think no one ever expected that such an addon would appear on our good old woltk. Thank you/

**Comment by bkader** [comment]
Hello @MaelKoT and thanks for reporting this. Glad you like the backport of this addon and happy that you like it.
Technically, this bug should not happen because of this:
```lua
local nameplate = LibNameplate:GetNameplateByGUID(guid)
```
As you can see above, nameplates are being handling using GUID instead of names, so I have no idea why it's happening to you and I don't think I can ever trigger the same bug to check it :( .. I will keep trying and when I figure out the problem I will update the addon.

**Comment by MaelKoT** [comment]
I checked with default blizzard nameplates - and this problem does not appear. So the problem is in ELVUI
:( sadge, I really love elvui nameplates (and his of buffs / debuffs module for nameplates)
____
One more problem, I decided not to create a separate topic for it
![image](https://user-images.githubusercontent.com/2527033/109660585-17c5d600-7b7a-11eb-8424-218ad5fb28b4.png)
In the addon, you can adjust transparency for text of damage on the target / off-targets; but in fact, parameter is always taken from off-target alpha values.

**Comment by MaelKoT** [comment]
And there is the video

https://youtu.be/cGtiRmpZxBE
Damage appears above the last created nameplate, or something like that =_=

**Comment by bkader** [comment]
@MaelKoT I have tried everything to have the same bug, nothing happened. However, I didn't try with a DK yet.
For the other bug, about different opacity, I have fixed it and updated the addon, try to download it again and let me know.
As for "Animation Speed", the original author named it so, so blame him lol .. The higher it is, the longer the animation is.

**Comment by MaelKoT** [comment]
@bkader are you shure, you turned on ElvUI Nameplates? Because i deleted all WTF, and tested with only 3 addons (NameplateSCT_WoTLK + ElvUI + ElvUI_Options) - and still have this bug/

And I'm tested NameplateSCT_WoTLK with all nameplate addons, what i can find, and it didnt work only with ELVUI :(

-Blizzard nameplates (default): OK
-TidyPlates (with all skins): OK
-DocsUI_Nameplates: OK
-Aloft: OK
-caelNamePlates: OK
-ElvUI: Sadge ;(

__
opacity bug fixed, ty

**Comment by Zidras** [comment]
FWIW, I also had this issue when I tested the addon.

**Comment by Dokho0** [comment]
Me too :(

**Comment by bkader** [comment]
Let me guess! ElvUI?

**Comment by Zidras** [comment]
With elvui yes. Don't know the cause of it

**Comment by bkader** [comment]
This is fixed. Update the addon and check please.

**Comment by MaelKoT** [comment]
Unfortunatelly, this fix broke https://github.com/bkader/PlateBuffs_WoTLK ;(
No errors, but debuffs just doesnt appear on nameplates...

**Comment by bkader** [comment]
You are using the combination of **ElvUI** + **NameplateSCT ** + **PlateBuffs**?!

**Comment by bkader** [comment]
https://user-images.githubusercontent.com/4732702/119229704-1f5da100-bb11-11eb-9238-74ff8f0d4ec3.mp4

**Comment by rathodkanishk** [comment]
Despite my downloading the latest version, I still have the same problems as outlined by @MaelKoT and @Zidras. 
In addition to those issues, off-target damage isn't shown at all no matter what I try to do. 

I am using ElvUI as well - is there something I can do to fix it? I am unsure of whats causing the problem.

**Comment by jukefr** [comment]
Leaving a comment to say that i'm facing the same issue running latest main of this plugin and latest main of https://github.com/ElvUI-WotLK/ElvUI
I haven't tried to see much of what is happening in the code but here are the in game symptoms, the stuff in parentheses is stuff im assuming from having it happen for like 6h of gameplay with it but im not necessarily sure they are required conditions :
- (if other nameplates are rendered on screen) when i engage combat sometimes the numbers wont work
- if other nameplates are rendered on screen when i engage combat sometimes the numbers will show on another nameplate that is in the current render field of view
- the very interesting thing however is that in **100%** of the cases, if i turn my camera around (stop rendering the plates) and back around to them then they will display the numbers
- if i engage multiple targets _rarely_ do the numbers show for more than one target (it happens, but most of the time will only work on one target)
- the getting them out of render view and back in for multiple targets usually won't fix the numbers not showing on multiple of them however

**Comment by bkader** [comment]
Hello @jukefr .. To reply to your points:
* Nameplates out of screen are unknown nameplates, it means that you lost their **GUIDs** which are used to display the damage, depending on the combat log. So, you have the GUID that's taking damage but no nameplate cached for it, that's why it doesn't show.
* Turning your camera doesn't fix the problem, you are just resetting cached nameplates, that's all. As mentioned in the point above: they appear; you have a valid unitId (target, mouseover, focus...) so their GUIDs are cached, they take damage, the CLEU has GUIDs thus numbers are shown on the nameplates. Turning your camera away hide nameplates as they never existed, so their cached GUIDs are deleted.
* As for number on wrong nameplates, that has something to do with ElvUI nameplates, I have done some modifications but didn't have the chance nor the time to test and validate, we will see.

**Comment by jukefr** [comment]
I'm sorry I think I explain it badly in text so just to make sure here are two small gifs :

![a demo gif of the bug, the numbers dont show except after i do a 360 with the camera](https://user-images.githubusercontent.com/2154296/150582754-f9c438d3-66c4-44be-b0e6-1a22afc9914a.gif)


and the very next mob

![the same bug happens on the next mob and the same getting out of view trick fixes it again](https://user-images.githubusercontent.com/2154296/150582643-5a0498c8-7eac-489e-bfe1-ec7ff680347f.gif)
